### ISSUE TITLE
"RootStoreBase implicitly has type 'any' ..." when generating models for a Hasura schema

### ISSUE THREAD

**Issue by beepsoft** [mobxjs/mst-gql#72]
Hi,

I'm trying to generate mst-gql models from a [Hasura](https://hasura.io/) (v1.0.0-beta.4) generated graphql shema.

This is the database schema (basic Todo) I use in postgresql:

```
create table todo
(
	id bigserial not null
		constraint todo_pkey
			primary key,
	text text not null,
	complete boolean not null
);
```

Hasura generates this schema for it

```
schema {
  query: query_root
  mutation: mutation_root
  subscription: subscription_root
}

scalar bigint

# expression to compare columns of type bigint. All fields are combined with logical 'AND'.
input bigint_comparison_exp {
  _eq: bigint
  _gt: bigint
  _gte: bigint
  _in: [bigint]
  _is_null: Boolean
  _lt: bigint
  _lte: bigint
  _neq: bigint
  _nin: [bigint]
}

# expression to compare columns of type boolean. All fields are combined with logical 'AND'.
input boolean_comparison_exp {
  _eq: Boolean
  _gt: Boolean
  _gte: Boolean
  _in: [Boolean]
  _is_null: Boolean
  _lt: Boolean
  _lte: Boolean
  _neq: Boolean
  _nin: [Boolean]
}

# conflict action
enum conflict_action {
  # ignore the insert on this row
  ignore

  # update the row with the given values
  update
}

# mutation root
type mutation_root {
  # delete data from the table: "todo"
  delete_todo(
    # filter the rows which have to be deleted
    where: todo_bool_exp!
  ): todo_mutation_response

  # insert data into the table: "todo"
  insert_todo(
    # the rows to be inserted
    objects: [todo_insert_input!]!

    # on conflict condition
    on_conflict: todo_on_conflict
  ): todo_mutation_response

  # update data of the table: "todo"
  update_todo(
    # increments the integer columns with given value of the filtered values
    _inc: todo_inc_input

    # sets the columns of the filtered rows to the given values
    _set: todo_set_input

    # filter the rows which have to be updated
    where: todo_bool_exp!
  ): todo_mutation_response
}

# column ordering options
enum order_by {
  # in the ascending order, nulls last
  asc

  # in the ascending order, nulls first
  asc_nulls_first

  # in the ascending order, nulls last
  asc_nulls_last

  # in the descending order, nulls first
  desc

  # in the descending order, nulls first
  desc_nulls_first

  # in the descending order, nulls last
  desc_nulls_last
}

# query root
type query_root {
  # fetch data from the table: "todo"
  todo(
    # distinct select on columns
    distinct_on: [todo_select_column!]

    # limit the nuber of rows returned
    limit: Int

    # skip the first n rows. Use only with order_by
    offset: Int

    # sort the rows by one or more columns
    order_by: [todo_order_by!]

    # filter the rows returned
    where: todo_bool_exp
  ): [todo!]!

  # fetch aggregated fields from the table: "todo"
  todo_aggregate(
    # distinct select on columns
    distinct_on: [todo_select_column!]

    # limit the nuber of rows returned
    limit: Int

    # skip the first n rows. Use only with order_by
    offset: Int

    # sort the rows by one or more columns
    order_by: [todo_order_by!]

    # filter the rows returned
    where: todo_bool_exp
  ): todo_aggregate!

  # fetch data from the table: "todo" using primary key columns
  todo_by_pk(id: bigint!): todo
}

# subscription root
type subscription_root {
  # fetch data from the table: "todo"
  todo(
    # distinct select on columns
    distinct_on: [todo_select_column!]

    # limit the nuber of rows returned
    limit: Int

    # skip the first n rows. Use only with order_by
    offset: Int

    # sort the rows by one or more columns
    order_by: [todo_order_by!]

    # filter the rows returned
    where: todo_bool_exp
  ): [todo!]!

  # fetch aggregated fields from the table: "todo"
  todo_aggregate(
    # distinct select on columns
    distinct_on: [todo_select_column!]

    # limit the nuber of rows returned
    limit: Int

    # skip the first n rows. Use only with order_by
    offset: Int

    # sort the rows by one or more columns
    order_by: [todo_order_by!]

    # filter the rows returned
    where: todo_bool_exp
  ): todo_aggregate!

  # fetch data from the table: "todo" using primary key columns
  todo_by_pk(id: bigint!): todo
}

# expression to compare columns of type text. All fields are combined with logical 'AND'.
input text_comparison_exp {
  _eq: String
  _gt: String
  _gte: String
  _ilike: String
  _in: [String]
  _is_null: Boolean
  _like: String
  _lt: String
  _lte: String
  _neq: String
  _nilike: String
  _nin: [String]
  _nlike: String
  _nsimilar: String
  _similar: String
}

# columns and relationships of "todo"
type todo {
  complete: Boolean!
  id: bigint!
  text: String!
}

# aggregated selection of "todo"
type todo_aggregate {
  aggregate: todo_aggregate_fields
  nodes: [todo!]!
}

# aggregate fields of "todo"
type todo_aggregate_fields {
  avg: todo_avg_fields
  count(columns: [todo_select_column!], distinct: Boolean): Int
  max: todo_max_fields
  min: todo_min_fields
  stddev: todo_stddev_fields
  stddev_pop: todo_stddev_pop_fields
  stddev_samp: todo_stddev_samp_fields
  sum: todo_sum_fields
  var_pop: todo_var_pop_fields
  var_samp: todo_var_samp_fields
  variance: todo_variance_fields
}

# order by aggregate values of table "todo"
input todo_aggregate_order_by {
  avg: todo_avg_order_by
  count: order_by
  max: todo_max_order_by
  min: todo_min_order_by
  stddev: todo_stddev_order_by
  stddev_pop: todo_stddev_pop_order_by
  stddev_samp: todo_stddev_samp_order_by
  sum: todo_sum_order_by
  var_pop: todo_var_pop_order_by
  var_samp: todo_var_samp_order_by
  variance: todo_variance_order_by
}

# input type for inserting array relation for remote table "todo"
input todo_arr_rel_insert_input {
  data: [todo_insert_input!]!
  on_conflict: todo_on_conflict
}

# aggregate avg on columns
type todo_avg_fields {
  id: Float
}

# order by avg() on columns of table "todo"
input todo_avg_order_by {
  id: order_by
}

# Boolean expression to filter rows from the table "todo". All fields are combined with a logical 'AND'.
input todo_bool_exp {
  _and: [todo_bool_exp]
  _not: todo_bool_exp
  _or: [todo_bool_exp]
  complete: boolean_comparison_exp
  id: bigint_comparison_exp
  text: text_comparison_exp
}

# unique or primary key constraints on table "todo"
enum todo_constraint {
  # unique or primary key constraint
  todo_pkey
}

# input type for incrementing integer columne in table "todo"
input todo_inc_input {
  id: bigint
}

# input type for inserting data into table "todo"
input todo_insert_input {
  complete: Boolean
  id: bigint
  text: String
}

# aggregate max on columns
type todo_max_fields {
  id: bigint
  text: String
}

# order by max() on columns of table "todo"
input todo_max_order_by {
  id: order_by
  text: order_by
}

# aggregate min on columns
type todo_min_fields {
  id: bigint
  text: String
}

# order by min() on columns of table "todo"
input todo_min_order_by {
  id: order_by
  text: order_by
}

# response of any mutation on the table "todo"
type todo_mutation_response {
  # number of affected rows by the mutation
  affected_rows: Int!

  # data of the affected rows by the mutation
  returning: [todo!]!
}

# input type for inserting object relation for remote table "todo"
input todo_obj_rel_insert_input {
  data: todo_insert_input!
  on_conflict: todo_on_conflict
}

# on conflict condition type for table "todo"
input todo_on_conflict {
  constraint: todo_constraint!
  update_columns: [todo_update_column!]!
}

# ordering options when selecting data from "todo"
input todo_order_by {
  complete: order_by
  id: order_by
  text: order_by
}

# select columns of table "todo"
enum todo_select_column {
  # column name
  complete

  # column name
  id

  # column name
  text
}

# input type for updating data in table "todo"
input todo_set_input {
  complete: Boolean
  id: bigint
  text: String
}

# aggregate stddev on columns
type todo_stddev_fields {
  id: Float
}

# order by stddev() on columns of table "todo"
input todo_stddev_order_by {
  id: order_by
}

# aggregate stddev_pop on columns
type todo_stddev_pop_fields {
  id: Float
}

# order by stddev_pop() on columns of table "todo"
input todo_stddev_pop_order_by {
  id: order_by
}

# aggregate stddev_samp on columns
type todo_stddev_samp_fields {
  id: Float
}

# order by stddev_samp() on columns of table "todo"
input todo_stddev_samp_order_by {
  id: order_by
}

# aggregate sum on columns
type todo_sum_fields {
  id: bigint
}

# order by sum() on columns of table "todo"
input todo_sum_order_by {
  id: order_by
}

# update columns of table "todo"
enum todo_update_column {
  # column name
  complete

  # column name
  id

  # column name
  text
}

# aggregate var_pop on columns
type todo_var_pop_fields {
  id: Float
}

# order by var_pop() on columns of table "todo"
input todo_var_pop_order_by {
  id: order_by
}

# aggregate var_samp on columns
type todo_var_samp_fields {
  id: Float
}

# order by var_samp() on columns of table "todo"
input todo_var_samp_order_by {
  id: order_by
}

# aggregate variance on columns
type todo_variance_fields {
  id: Float
}

# order by variance() on columns of table "todo"
input todo_variance_order_by {
  id: order_by
}
```

When I run `mst-gql --format ts todo-schema.graphql` and try to use the generated models, useQuery, etc. I get no code completion because the type of RootStoreBase, RootStore etc. is always 'any'. For these types I get an TS error like:

```Error:(51, 14) TS7022: 'RootStoreBase' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.```

Unfortunately I don't know the internals of mst and also not an expert of Typescript, so I could not figure out what causes this problem.

Do you have any Idea?

_Note: I started off from a more complex data schema and thought that caused the problems. Then I tried this single table Todo use case and it produced the same errors._

**Comment by chrisdrackett** [comment]
@beepsoft this is a known issue, see #45 for more info. The ideal plan is to generate the types automatically, it just hasn't been attempted yet!

**Comment by mweststrate** [comment]
This seems to be a regression, and might very well be fixed by #69

**Comment by beepsoft** [comment]
@mweststrate The commits in #69 seem to fix this issue. Thanks! 👍

**Comment by beepsoft** [comment]
@mweststrate I also tried it with a bit more complex postgresql/Hasura schema (based on https://github.com/callicoder/spring-security-react-ant-design-polls-app). For this I still get "RootStoreBase implicitly has type 'any' ..." error:

```
schema {
  query: query_root
  mutation: mutation_root
  subscription: subscription_root
}

scalar bigint

# expression to compare columns of type bigint. All fields are combined with logical 'AND'.
input bigint_comparison_exp {
  _eq: bigint
  _gt: bigint
  _gte: bigint
  _in: [bigint]
  _is_null: Boolean
  _lt: bigint
  _lte: bigint
  _neq: bigint
  _nin: [bigint]
}

# columns and relationships of "choices"
type choices {
  id: bigint!

  # An object relationship
  poll: polls!
  poll_id: bigint!
  text: String

  # An array relationship
  votes(
    # distinct select on columns
    distinct_on: [votes_select_column!]

    # limit the nuber of rows returned
    limit: Int

    # skip the first n rows. Use only with order_by
    offset: Int

    # sort the rows by one or more columns
    order_by: [votes_order_by!]

    # filter the rows returned
    where: votes_bool_exp
  ): [votes!]!

  # An aggregated array relationship
  votes_aggregate(
    # distinct select on columns
    distinct_on: [votes_select_column!]

    # limit the nuber of rows returned
    limit: Int

    # skip the first n rows. Use only with order_by
    offset: Int

    # sort the rows by one or more columns
    order_by: [votes_order_by!]

    # filter the rows returned
    where: votes_bool_exp
  ): votes_aggregate!
}

# aggregated selection of "choices"
type choices_aggregate {
  aggregate: choices_aggregate_fields
  nodes: [choices!]!
}

# aggregate fields of "choices"
type choices_aggregate_fields {
  avg: choices_avg_fields
  count(columns: [choices_select_column!], distinct: Boolean): Int
  max: choices_max_fields
  min: choices_min_fields
  stddev: choices_stddev_fields
  stddev_pop: choices_stddev_pop_fields
  stddev_samp: choices_stddev_samp_fields
  sum: choices_sum_fields
  var_pop: choices_var_pop_fields
  var_samp: choices_var_samp_fields
  variance: choices_variance_fields
}

# order by aggregate values of table "choices"
input choices_aggregate_order_by {
  avg: choices_avg_order_by
  count: order_by
  max: choices_max_order_by
  min: choices_min_order_by
  stddev: choices_stddev_order_by
  stddev_pop: choices_stddev_pop_order_by
  stddev_samp: choices_stddev_samp_order_by
  sum: choices_sum_order_by
  var_pop: choices_var_pop_order_by
  var_samp: choices_var_samp_order_by
  variance: choices_variance_order_by
}

# input type for inserting array relation for remote table "choices"
input choices_arr_rel_insert_input {
  data: [choices_insert_input!]!
  on_conflict: choices_on_conflict
}

# aggregate avg on columns
type choices_avg_fields {
  id: Float
  poll_id: Float
}

# order by avg() on columns of table "choices"
input choices_avg_order_by {
  id: order_by
  poll_id: order_by
}

# Boolean expression to filter rows from the table "choices". All fields are combined with a logical 'AND'.
input choices_bool_exp {
  _and: [choices_bool_exp]
  _not: choices_bool_exp
  _or: [choices_bool_exp]
  id: bigint_comparison_exp
  poll: polls_bool_exp
  poll_id: bigint_comparison_exp
  text: varchar_comparison_exp
  votes: votes_bool_exp
}

# unique or primary key constraints on table "choices"
enum choices_constraint {
  # unique or primary key constraint
  choices_pkey
}

# input type for incrementing integer columne in table "choices"
input choices_inc_input {
  id: bigint
  poll_id: bigint
}

# input type for inserting data into table "choices"
input choices_insert_input {
  id: bigint
  poll: polls_obj_rel_insert_input
  poll_id: bigint
  text: String
  votes: votes_arr_rel_insert_input
}

# aggregate max on columns
type choices_max_fields {
  id: bigint
  poll_id: bigint
  text: String
}

# order by max() on columns of table "choices"
input choices_max_order_by {
  id: order_by
  poll_id: order_by
  text: order_by
}

# aggregate min on columns
type choices_min_fields {
  id: bigint
  poll_id: bigint
  text: String
}

# order by min() on columns of table "choices"
input choices_min_order_by {
  id: order_by
  poll_id: order_by
  text: order_by
}

# response of any mutation on the table "choices"
type choices_mutation_response {
  # number of affected rows by the mutation
  affected_rows: Int!

  # data of the affected rows by the mutation
  returning: [choices!]!
}

# input type for inserting object relation for remote table "choices"
input choices_obj_rel_insert_input {
  data: choices_insert_input!
  on_conflict: choices_on_conflict
}

# on conflict condition type for table "choices"
input choices_on_conflict {
  constraint: choices_constraint!
  update_columns: [choices_update_column!]!
}

# ordering options when selecting data from "choices"
input choices_order_by {
  id: order_by
  poll: polls_order_by
  poll_id: order_by
  text: order_by
  votes_aggregate: votes_aggregate_order_by
}

# select columns of table "choices"
enum choices_select_column {
  # column name
  id

  # column name
  poll_id

  # column name
  text
}

# input type for updating data in table "choices"
input choices_set_input {
  id: bigint
  poll_id: bigint
  text: String
}

# aggregate stddev on columns
type choices_stddev_fields {
  id: Float
  poll_id: Float
}

# order by stddev() on columns of table "choices"
input choices_stddev_order_by {
  id: order_by
  poll_id: order_by
}

# aggregate stddev_pop on columns
type choices_stddev_pop_fields {
  id: Float
  poll_id: Float
}

# order by stddev_pop() on columns of table "choices"
input choices_stddev_pop_order_by {
  id: order_by
  poll_id: order_by
}

# aggregate stddev_samp on columns
type choices_stddev_samp_fields {
  id: Float
  poll_id: Float
}

# order by stddev_samp() on columns of table "choices"
input choices_stddev_samp_order_by {
  id: order_by
  poll_id: order_by
}

# aggregate sum on columns
type choices_sum_fields {
  id: bigint
  poll_id: bigint
}

# order by sum() on columns of table "choices"
input choices_sum_order_by {
  id: order_by
  poll_id: order_by
}

# update columns of table "choices"
enum choices_update_column {
  # column name
  id

  # column name
  poll_id

  # column name
  text
}

# aggregate var_pop on columns
type choices_var_pop_fields {
  id: Float
  poll_id: Float
}

# order by var_pop() on columns of table "choices"
input choices_var_pop_order_by {
  id: order_by
  poll_id: order_by
}

# aggregate var_samp on columns
type choices_var_samp_fields {
  id: Float
  poll_id: Float
}

# order by var_samp() on columns of table "choices"
input choices_var_samp_order_by {
  id: order_by
  poll_id: order_by
}

# aggregate variance on columns
type choices_variance_fields {
  id: Float
  poll_id: Float
}

# order by variance() on columns of table "choices"
input choices_variance_order_by {
  id: order_by
  poll_id: order_by
}

# conflict action
enum conflict_action {
  # ignore the insert on this row
  ignore

  # update the row with the given values
  update
}

# mutation root
type mutation_root {
  # delete data from the table: "choices"
  delete_choices(
    # filter the rows which have to be deleted
    where: choices_bool_exp!
  ): choices_mutation_response

  # delete data from the table: "polls"
  delete_polls(
    # filter the rows which have to be deleted
    where: polls_bool_exp!
  ): polls_mutation_response

  # delete data from the table: "roles"
  delete_roles(
    # filter the rows which have to be deleted
    where: roles_bool_exp!
  ): roles_mutation_response

  # delete data from the table: "user_roles"
  delete_user_roles(
    # filter the rows which have to be deleted
    where: user_roles_bool_exp!
  ): user_roles_mutation_response

  # delete data from the table: "users"
  delete_users(
    # filter the rows which have to be deleted
    where: users_bool_exp!
  ): users_mutation_response

  # delete data from the table: "votes"
  delete_votes(
    # filter the rows which have to be deleted
    where: votes_bool_exp!
  ): votes_mutation_response

  # insert data into the table: "choices"
  insert_choices(
    # the rows to be inserted
    objects: [choices_insert_input!]!

    # on conflict condition
    on_conflict: choices_on_conflict
  ): choices_mutation_response

  # insert data into the table: "polls"
  insert_polls(
    # the rows to be inserted
    objects: [polls_insert_input!]!

    # on conflict condition
    on_conflict: polls_on_conflict
  ): polls_mutation_response

  # insert data into the table: "roles"
  insert_roles(
    # the rows to be inserted
    objects: [roles_insert_input!]!

    # on conflict condition
    on_conflict: roles_on_conflict
  ): roles_mutation_response

  # insert data into the table: "user_roles"
  insert_user_roles(
    # the rows to be inserted
    objects: [user_roles_insert_input!]!

    # on conflict condition
    on_conflict: user_roles_on_conflict
  ): user_roles_mutation_response

  # insert data into the table: "users"
  insert_users(
    # the rows to be inserted
    objects: [users_insert_input!]!

    # on conflict condition
    on_conflict: users_on_conflict
  ): users_mutation_response

  # insert data into the table: "votes"
  insert_votes(
    # the rows to be inserted
    objects: [votes_insert_input!]!

    # on conflict condition
    on_conflict: votes_on_conflict
  ): votes_mutation_response

  # update data of the table: "choices"
  update_choices(
    # increments the integer columns with given value of the filtered values
    _inc: choices_inc_input

    # sets the columns of the filtered rows to the given values
    _set: choices_set_input

    # filter the rows which have to be updated
    where: choices_bool_exp!
  ): choices_mutation_response

  # update data of the table: "polls"
  update_polls(
    # increments the integer columns with given value of the filtered values
    _inc: polls_inc_input

    # sets the columns of the filtered rows to the given values
    _set: polls_set_input

    # filter the rows which have to be updated
    where: polls_bool_exp!
  ): polls_mutation_response

  # update data of the table: "roles"
  update_roles(
    # increments the integer columns with given value of the filtered values
    _inc: roles_inc_input

    # sets the columns of the filtered rows to the given values
    _set: roles_set_input

    # filter the rows which have to be updated
    where: roles_bool_exp!
  ): roles_mutation_response

  # update data of the table: "user_roles"
  update_user_roles(
    # increments the integer columns with given value of the filtered values
    _inc: user_roles_inc_input

    # sets the columns of the filtered rows to the given values
    _set: user_roles_set_input

    # filter the rows which have to be updated
    where: user_roles_bool_exp!
  ): user_roles_mutation_response

  # update data of the table: "users"
  update_users(
    # increments the integer columns with given value of the filtered values
    _inc: users_inc_input

    # sets the columns of the filtered rows to the given values
    _set: users_set_input

    # filter the rows which have to be updated
    where: users_bool_exp!
  ): users_mutation_response

  # update data of the table: "votes"
  update_votes(
    # increments the integer columns with given value of the filtered values
    _inc: votes_inc_input

    # sets the columns of the filtered rows to the given values
    _set: votes_set_input

    # filter the rows which have to be updated
    where: votes_bool_exp!
  ): votes_mutation_response
}

# column ordering options
enum order_by {
  # in the ascending order, nulls last
  asc

  # in the ascending order, nulls first
  asc_nulls_first

  # in the ascending order, nulls last
  asc_nulls_last

  # in the descending order, nulls first
  desc

  # in the descending order, nulls first
  desc_nulls_first

  # in the descending order, nulls last
  desc_nulls_last
}

# columns and relationships of "polls"
type polls {
  # An array relationship
  choices(
    # distinct select on columns
    distinct_on: [choices_select_column!]

    # limit the nuber of rows returned
    limit: Int

    # skip the first n rows. Use only with order_by
    offset: Int

    # sort the rows by one or more columns
    order_by: [choices_order_by!]

    # filter the rows returned
    where: choices_bool_exp
  ): [choices!]!

  # An aggregated array relationship
  choices_aggregate(
    # distinct select on columns
    distinct_on: [choices_select_column!]

    # limit the nuber of rows returned
    limit: Int

    # skip the first n rows. Use only with order_by
    offset: Int

    # sort the rows by one or more columns
    order_by: [choices_order_by!]

    # filter the rows returned
    where: choices_bool_exp
  ): choices_aggregate!
  created_at: timestamp
  created_by: bigint
  expiration_date_time: timestamp!
  id: bigint!
  question: String
  updated_at: timestamp
  updated_by: bigint

  # An array relationship
  votes(
    # distinct select on columns
    distinct_on: [votes_select_column!]

    # limit the nuber of rows returned
    limit: Int

    # skip the first n rows. Use only with order_by
    offset: Int

    # sort the rows by one or more columns
    order_by: [votes_order_by!]

    # filter the rows returned
    where: votes_bool_exp
  ): [votes!]!

  # An aggregated array relationship
  votes_aggregate(
    # distinct select on columns
    distinct_on: [votes_select_column!]

    # limit the nuber of rows returned
    limit: Int

    # skip the first n rows. Use only with order_by
    offset: Int

    # sort the rows by one or more columns
    order_by: [votes_order_by!]

    # filter the rows returned
    where: votes_bool_exp
  ): votes_aggregate!
}

# aggregated selection of "polls"
type polls_aggregate {
  aggregate: polls_aggregate_fields
  nodes: [polls!]!
}

# aggregate fields of "polls"
type polls_aggregate_fields {
  avg: polls_avg_fields
  count(columns: [polls_select_column!], distinct: Boolean): Int
  max: polls_max_fields
  min: polls_min_fields
  stddev: polls_stddev_fields
  stddev_pop: polls_stddev_pop_fields
  stddev_samp: polls_stddev_samp_fields
  sum: polls_sum_fields
  var_pop: polls_var_pop_fields
  var_samp: polls_var_samp_fields
  variance: polls_variance_fields
}

# order by aggregate values of table "polls"
input polls_aggregate_order_by {
  avg: polls_avg_order_by
  count: order_by
  max: polls_max_order_by
  min: polls_min_order_by
  stddev: polls_stddev_order_by
  stddev_pop: polls_stddev_pop_order_by
  stddev_samp: polls_stddev_samp_order_by
  sum: polls_sum_order_by
  var_pop: polls_var_pop_order_by
  var_samp: polls_var_samp_order_by
  variance: polls_variance_order_by
}

# input type for inserting array relation for remote table "polls"
input polls_arr_rel_insert_input {
  data: [polls_insert_input!]!
  on_conflict: polls_on_conflict
}

# aggregate avg on columns
type polls_avg_fields {
  created_by: Float
  id: Float
  updated_by: Float
}

# order by avg() on columns of table "polls"
input polls_avg_order_by {
  created_by: order_by
  id: order_by
  updated_by: order_by
}

# Boolean expression to filter rows from the table "polls". All fields are combined with a logical 'AND'.
input polls_bool_exp {
  _and: [polls_bool_exp]
  _not: polls_bool_exp
  _or: [polls_bool_exp]
  choices: choices_bool_exp
  created_at: timestamp_comparison_exp
  created_by: bigint_comparison_exp
  expiration_date_time: timestamp_comparison_exp
  id: bigint_comparison_exp
  question: varchar_comparison_exp
  updated_at: timestamp_comparison_exp
  updated_by: bigint_comparison_exp
  votes: votes_bool_exp
}

# unique or primary key constraints on table "polls"
enum polls_constraint {
  # unique or primary key constraint
  polls_pkey
}

# input type for incrementing integer columne in table "polls"
input polls_inc_input {
  created_by: bigint
  id: bigint
  updated_by: bigint
}

# input type for inserting data into table "polls"
input polls_insert_input {
  choices: choices_arr_rel_insert_input
  created_at: timestamp
  created_by: bigint
  expiration_date_time: timestamp
  id: bigint
  question: String
  updated_at: timestamp
  updated_by: bigint
  votes: votes_arr_rel_insert_input
}

# aggregate max on columns
type polls_max_fields {
  created_by: bigint
  id: bigint
  question: String
  updated_by: bigint
}

# order by max() on columns of table "polls"
input polls_max_order_by {
  created_by: order_by
  id: order_by
  question: order_by
  updated_by: order_by
}

# aggregate min on columns
type polls_min_fields {
  created_by: bigint
  id: bigint
  question: String
  updated_by: bigint
}

# order by min() on columns of table "polls"
input polls_min_order_by {
  created_by: order_by
  id: order_by
  question: order_by
  updated_by: order_by
}

# response of any mutation on the table "polls"
type polls_mutation_response {
  # number of affected rows by the mutation
  affected_rows: Int!

  # data of the affected rows by the mutation
  returning: [polls!]!
}

# input type for inserting object relation for remote table "polls"
input polls_obj_rel_insert_input {
  data: polls_insert_input!
  on_conflict: polls_on_conflict
}

# on conflict condition type for table "polls"
input polls_on_conflict {
  constraint: polls_constraint!
  update_columns: [polls_update_column!]!
}

# ordering options when selecting data from "polls"
input polls_order_by {
  choices_aggregate: choices_aggregate_order_by
  created_at: order_by
  created_by: order_by
  expiration_date_time: order_by
  id: order_by
  question: order_by
  updated_at: order_by
  updated_by: order_by
  votes_aggregate: votes_aggregate_order_by
}

# select columns of table "polls"
enum polls_select_column {
  # column name
  created_at

  # column name
  created_by

  # column name
  expiration_date_time

  # column name
  id

  # column name
  question

  # column name
  updated_at

  # column name
  updated_by
}

# input type for updating data in table "polls"
input polls_set_input {
  created_at: timestamp
  created_by: bigint
  expiration_date_time: timestamp
  id: bigint
  question: String
  updated_at: timestamp
  updated_by: bigint
}

# aggregate stddev on columns
type polls_stddev_fields {
  created_by: Float
  id: Float
  updated_by: Float
}

# order by stddev() on columns of table "polls"
input polls_stddev_order_by {
  created_by: order_by
  id: order_by
  updated_by: order_by
}

# aggregate stddev_pop on columns
type polls_stddev_pop_fields {
  created_by: Float
  id: Float
  updated_by: Float
}

# order by stddev_pop() on columns of table "polls"
input polls_stddev_pop_order_by {
  created_by: order_by
  id: order_by
  updated_by: order_by
}

# aggregate stddev_samp on columns
type polls_stddev_samp_fields {
  created_by: Float
  id: Float
  updated_by: Float
}

# order by stddev_samp() on columns of table "polls"
input polls_stddev_samp_order_by {
  created_by: order_by
  id: order_by
  updated_by: order_by
}

# aggregate sum on columns
type polls_sum_fields {
  created_by: bigint
  id: bigint
  updated_by: bigint
}

# order by sum() on columns of table "polls"
input polls_sum_order_by {
  created_by: order_by
  id: order_by
  updated_by: order_by
}

# update columns of table "polls"
enum polls_update_column {
  # column name
  created_at

  # column name
  created_by

  # column name
  expiration_date_time

  # column name
  id

  # column name
  question

  # column name
  updated_at

  # column name
  updated_by
}

# aggregate var_pop on columns
type polls_var_pop_fields {
  created_by: Float
  id: Float
  updated_by: Float
}

# order by var_pop() on columns of table "polls"
input polls_var_pop_order_by {
  created_by: order_by
  id: order_by
  updated_by: order_by
}

# aggregate var_samp on columns
type polls_var_samp_fields {
  created_by: Float
  id: Float
  updated_by: Float
}

# order by var_samp() on columns of table "polls"
input polls_var_samp_order_by {
  created_by: order_by
  id: order_by
  updated_by: order_by
}

# aggregate variance on columns
type polls_variance_fields {
  created_by: Float
  id: Float
  updated_by: Float
}

# order by variance() on columns of table "polls"
input polls_variance_order_by {
  created_by: order_by
  id: order_by
  updated_by: order_by
}

# query root
type query_root {
  # fetch data from the table: "choices"
  choices(
    # distinct select on columns
    distinct_on: [choices_select_column!]

    # limit the nuber of rows returned
    limit: Int

    # skip the first n rows. Use only with order_by
    offset: Int

    # sort the rows by one or more columns
    order_by: [choices_order_by!]

    # filter the rows returned
    where: choices_bool_exp
  ): [choices!]!

  # fetch aggregated fields from the table: "choices"
  choices_aggregate(
    # distinct select on columns
    distinct_on: [choices_select_column!]

    # limit the nuber of rows returned
    limit: Int

    # skip the first n rows. Use only with order_by
    offset: Int

    # sort the rows by one or more columns
    order_by: [choices_order_by!]

    # filter the rows returned
    where: choices_bool_exp
  ): choices_aggregate!

  # fetch data from the table: "choices" using primary key columns
  choices_by_pk(id: bigint!): choices

  # fetch data from the table: "polls"
  polls(
    # distinct select on columns
    distinct_on: [polls_select_column!]

    # limit the nuber of rows returned
    limit: Int

    # skip the first n rows. Use only with order_by
    offset: Int

    # sort the rows by one or more columns
    order_by: [polls_order_by!]

    # filter the rows returned
    where: polls_bool_exp
  ): [polls!]!

  # fetch aggregated fields from the table: "polls"
  polls_aggregate(
    # distinct select on columns
    distinct_on: [polls_select_column!]

    # limit the nuber of rows returned
    limit: Int

    # skip the first n rows. Use only with order_by
    offset: Int

    # sort the rows by one or more columns
    order_by: [polls_order_by!]

    # filter the rows returned
    where: polls_bool_exp
  ): polls_aggregate!

  # fetch data from the table: "polls" using primary key columns
  polls_by_pk(id: bigint!): polls

  # fetch data from the table: "roles"
  roles(
    # distinct select on columns
    distinct_on: [roles_select_column!]

    # limit the nuber of rows returned
    limit: Int

    # skip the first n rows. Use only with order_by
    offset: Int

    # sort the rows by one or more columns
    order_by: [roles_order_by!]

    # filter the rows returned
    where: roles_bool_exp
  ): [roles!]!

  # fetch aggregated fields from the table: "roles"
  roles_aggregate(
    # distinct select on columns
    distinct_on: [roles_select_column!]

    # limit the nuber of rows returned
    limit: Int

    # skip the first n rows. Use only with order_by
    offset: Int

    # sort the rows by one or more columns
    order_by: [roles_order_by!]

    # filter the rows returned
    where: roles_bool_exp
  ): roles_aggregate!

  # fetch data from the table: "roles" using primary key columns
  roles_by_pk(id: bigint!): roles

  # fetch data from the table: "user_roles"
  user_roles(
    # distinct select on columns
    distinct_on: [user_roles_select_column!]

    # limit the nuber of rows returned
    limit: Int

    # skip the first n rows. Use only with order_by
    offset: Int

    # sort the rows by one or more columns
    order_by: [user_roles_order_by!]

    # filter the rows returned
    where: user_roles_bool_exp
  ): [user_roles!]!

  # fetch aggregated fields from the table: "user_roles"
  user_roles_aggregate(
    # distinct select on columns
    distinct_on: [user_roles_select_column!]

    # limit the nuber of rows returned
    limit: Int

    # skip the first n rows. Use only with order_by
    offset: Int

    # sort the rows by one or more columns
    order_by: [user_roles_order_by!]

    # filter the rows returned
    where: user_roles_bool_exp
  ): user_roles_aggregate!

  # fetch data from the table: "user_roles" using primary key columns
  user_roles_by_pk(role_id: bigint!, user_id: bigint!): user_roles

  # fetch data from the table: "users"
  users(
    # distinct select on columns
    distinct_on: [users_select_column!]

    # limit the nuber of rows returned
    limit: Int

    # skip the first n rows. Use only with order_by
    offset: Int

    # sort the rows by one or more columns
    order_by: [users_order_by!]

    # filter the rows returned
    where: users_bool_exp
  ): [users!]!

  # fetch aggregated fields from the table: "users"
  users_aggregate(
    # distinct select on columns
    distinct_on: [users_select_column!]

    # limit the nuber of rows returned
    limit: Int

    # skip the first n rows. Use only with order_by
    offset: Int

    # sort the rows by one or more columns
    order_by: [users_order_by!]

    # filter the rows returned
    where: users_bool_exp
  ): users_aggregate!

  # fetch data from the table: "users" using primary key columns
  users_by_pk(id: bigint!): users

  # fetch data from the table: "votes"
  votes(
    # distinct select on columns
    distinct_on: [votes_select_column!]

    # limit the nuber of rows returned
    limit: Int

    # skip the first n rows. Use only with order_by
    offset: Int

    # sort the rows by one or more columns
    order_by: [votes_order_by!]

    # filter the rows returned
    where: votes_bool_exp
  ): [votes!]!

  # fetch aggregated fields from the table: "votes"
  votes_aggregate(
    # distinct select on columns
    distinct_on: [votes_select_column!]

    # limit the nuber of rows returned
    limit: Int

    # skip the first n rows. Use only with order_by
    offset: Int

    # sort the rows by one or more columns
    order_by: [votes_order_by!]

    # filter the rows returned
    where: votes_bool_exp
  ): votes_aggregate!

  # fetch data from the table: "votes" using primary key columns
  votes_by_pk(id: bigint!): votes
}

# columns and relationships of "roles"
type roles {
  id: bigint!
  name: String

  # An array relationship
  user_roles(
    # distinct select on columns
    distinct_on: [user_roles_select_column!]

    # limit the nuber of rows returned
    limit: Int

    # skip the first n rows. Use only with order_by
    offset: Int

    # sort the rows by one or more columns
    order_by: [user_roles_order_by!]

    # filter the rows returned
    where: user_roles_bool_exp
  ): [user_roles!]!

  # An aggregated array relationship
  user_roles_aggregate(
    # distinct select on columns
    distinct_on: [user_roles_select_column!]

    # limit the nuber of rows returned
    limit: Int

    # skip the first n rows. Use only with order_by
    offset: Int

    # sort the rows by one or more columns
    order_by: [user_roles_order_by!]

    # filter the rows returned
    where: user_roles_bool_exp
  ): user_roles_aggregate!
}

# aggregated selection of "roles"
type roles_aggregate {
  aggregate: roles_aggregate_fields
  nodes: [roles!]!
}

# aggregate fields of "roles"
type roles_aggregate_fields {
  avg: roles_avg_fields
  count(columns: [roles_select_column!], distinct: Boolean): Int
  max: roles_max_fields
  min: roles_min_fields
  stddev: roles_stddev_fields
  stddev_pop: roles_stddev_pop_fields
  stddev_samp: roles_stddev_samp_fields
  sum: roles_sum_fields
  var_pop: roles_var_pop_fields
  var_samp: roles_var_samp_fields
  variance: roles_variance_fields
}

# order by aggregate values of table "roles"
input roles_aggregate_order_by {
  avg: roles_avg_order_by
  count: order_by
  max: roles_max_order_by
  min: roles_min_order_by
  stddev: roles_stddev_order_by
  stddev_pop: roles_stddev_pop_order_by
  stddev_samp: roles_stddev_samp_order_by
  sum: roles_sum_order_by
  var_pop: roles_var_pop_order_by
  var_samp: roles_var_samp_order_by
  variance: roles_variance_order_by
}

# input type for inserting array relation for remote table "roles"
input roles_arr_rel_insert_input {
  data: [roles_insert_input!]!
  on_conflict: roles_on_conflict
}

# aggregate avg on columns
type roles_avg_fields {
  id: Float
}

# order by avg() on columns of table "roles"
input roles_avg_order_by {
  id: order_by
}

# Boolean expression to filter rows from the table "roles". All fields are combined with a logical 'AND'.
input roles_bool_exp {
  _and: [roles_bool_exp]
  _not: roles_bool_exp
  _or: [roles_bool_exp]
  id: bigint_comparison_exp
  name: varchar_comparison_exp
  user_roles: user_roles_bool_exp
}

# unique or primary key constraints on table "roles"
enum roles_constraint {
  # unique or primary key constraint
  roles_pkey

  # unique or primary key constraint
  uk_nb4h0p6txrmfc0xbrd1kglp9t
}

# input type for incrementing integer columne in table "roles"
input roles_inc_input {
  id: bigint
}

# input type for inserting data into table "roles"
input roles_insert_input {
  id: bigint
  name: String
  user_roles: user_roles_arr_rel_insert_input
}

# aggregate max on columns
type roles_max_fields {
  id: bigint
  name: String
}

# order by max() on columns of table "roles"
input roles_max_order_by {
  id: order_by
  name: order_by
}

# aggregate min on columns
type roles_min_fields {
  id: bigint
  name: String
}

# order by min() on columns of table "roles"
input roles_min_order_by {
  id: order_by
  name: order_by
}

# response of any mutation on the table "roles"
type roles_mutation_response {
  # number of affected rows by the mutation
  affected_rows: Int!

  # data of the affected rows by the mutation
  returning: [roles!]!
}

# input type for inserting object relation for remote table "roles"
input roles_obj_rel_insert_input {
  data: roles_insert_input!
  on_conflict: roles_on_conflict
}

# on conflict condition type for table "roles"
input roles_on_conflict {
  constraint: roles_constraint!
  update_columns: [roles_update_column!]!
}

# ordering options when selecting data from "roles"
input roles_order_by {
  id: order_by
  name: order_by
  user_roles_aggregate: user_roles_aggregate_order_by
}

# select columns of table "roles"
enum roles_select_column {
  # column name
  id

  # column name
  name
}

# input type for updating data in table "roles"
input roles_set_input {
  id: bigint
  name: String
}

# aggregate stddev on columns
type roles_stddev_fields {
  id: Float
}

# order by stddev() on columns of table "roles"
input roles_stddev_order_by {
  id: order_by
}

# aggregate stddev_pop on columns
type roles_stddev_pop_fields {
  id: Float
}

# order by stddev_pop() on columns of table "roles"
input roles_stddev_pop_order_by {
  id: order_by
}

# aggregate stddev_samp on columns
type roles_stddev_samp_fields {
  id: Float
}

# order by stddev_samp() on columns of table "roles"
input roles_stddev_samp_order_by {
  id: order_by
}

# aggregate sum on columns
type roles_sum_fields {
  id: bigint
}

# order by sum() on columns of table "roles"
input roles_sum_order_by {
  id: order_by
}

# update columns of table "roles"
enum roles_update_column {
  # column name
  id

  # column name
  name
}

# aggregate var_pop on columns
type roles_var_pop_fields {
  id: Float
}

# order by var_pop() on columns of table "roles"
input roles_var_pop_order_by {
  id: order_by
}

# aggregate var_samp on columns
type roles_var_samp_fields {
  id: Float
}

# order by var_samp() on columns of table "roles"
input roles_var_samp_order_by {
  id: order_by
}

# aggregate variance on columns
type roles_variance_fields {
  id: Float
}

# order by variance() on columns of table "roles"
input roles_variance_order_by {
  id: order_by
}

# subscription root
type subscription_root {
  # fetch data from the table: "choices"
  choices(
    # distinct select on columns
    distinct_on: [choices_select_column!]

    # limit the nuber of rows returned
    limit: Int

    # skip the first n rows. Use only with order_by
    offset: Int

    # sort the rows by one or more columns
    order_by: [choices_order_by!]

    # filter the rows returned
    where: choices_bool_exp
  ): [choices!]!

  # fetch aggregated fields from the table: "choices"
  choices_aggregate(
    # distinct select on columns
    distinct_on: [choices_select_column!]

    # limit the nuber of rows returned
    limit: Int

    # skip the first n rows. Use only with order_by
    offset: Int

    # sort the rows by one or more columns
    order_by: [choices_order_by!]

    # filter the rows returned
    where: choices_bool_exp
  ): choices_aggregate!

  # fetch data from the table: "choices" using primary key columns
  choices_by_pk(id: bigint!): choices

  # fetch data from the table: "polls"
  polls(
    # distinct select on columns
    distinct_on: [polls_select_column!]

    # limit the nuber of rows returned
    limit: Int

    # skip the first n rows. Use only with order_by
    offset: Int

    # sort the rows by one or more columns
    order_by: [polls_order_by!]

    # filter the rows returned
    where: polls_bool_exp
  ): [polls!]!

  # fetch aggregated fields from the table: "polls"
  polls_aggregate(
    # distinct select on columns
    distinct_on: [polls_select_column!]

    # limit the nuber of rows returned
    limit: Int

    # skip the first n rows. Use only with order_by
    offset: Int

    # sort the rows by one or more columns
    order_by: [polls_order_by!]

    # filter the rows returned
    where: polls_bool_exp
  ): polls_aggregate!

  # fetch data from the table: "polls" using primary key columns
  polls_by_pk(id: bigint!): polls

  # fetch data from the table: "roles"
  roles(
    # distinct select on columns
    distinct_on: [roles_select_column!]

    # limit the nuber of rows returned
    limit: Int

    # skip the first n rows. Use only with order_by
    offset: Int

    # sort the rows by one or more columns
    order_by: [roles_order_by!]

    # filter the rows returned
    where: roles_bool_exp
  ): [roles!]!

  # fetch aggregated fields from the table: "roles"
  roles_aggregate(
    # distinct select on columns
    distinct_on: [roles_select_column!]

    # limit the nuber of rows returned
    limit: Int

    # skip the first n rows. Use only with order_by
    offset: Int

    # sort the rows by one or more columns
    order_by: [roles_order_by!]

    # filter the rows returned
    where: roles_bool_exp
  ): roles_aggregate!

  # fetch data from the table: "roles" using primary key columns
  roles_by_pk(id: bigint!): roles

  # fetch data from the table: "user_roles"
  user_roles(
    # distinct select on columns
    distinct_on: [user_roles_select_column!]

    # limit the nuber of rows returned
    limit: Int

    # skip the first n rows. Use only with order_by
    offset: Int

    # sort the rows by one or more columns
    order_by: [user_roles_order_by!]

    # filter the rows returned
    where: user_roles_bool_exp
  ): [user_roles!]!

  # fetch aggregated fields from the table: "user_roles"
  user_roles_aggregate(
    # distinct select on columns
    distinct_on: [user_roles_select_column!]

    # limit the nuber of rows returned
    limit: Int

    # skip the first n rows. Use only with order_by
    offset: Int

    # sort the rows by one or more columns
    order_by: [user_roles_order_by!]

    # filter the rows returned
    where: user_roles_bool_exp
  ): user_roles_aggregate!

  # fetch data from the table: "user_roles" using primary key columns
  user_roles_by_pk(role_id: bigint!, user_id: bigint!): user_roles

  # fetch data from the table: "users"
  users(
    # distinct select on columns
    distinct_on: [users_select_column!]

    # limit the nuber of rows returned
    limit: Int

    # skip the first n rows. Use only with order_by
    offset: Int

    # sort the rows by one or more columns
    order_by: [users_order_by!]

    # filter the rows returned
    where: users_bool_exp
  ): [users!]!

  # fetch aggregated fields from the table: "users"
  users_aggregate(
    # distinct select on columns
    distinct_on: [users_select_column!]

    # limit the nuber of rows returned
    limit: Int

    # skip the first n rows. Use only with order_by
    offset: Int

    # sort the rows by one or more columns
    order_by: [users_order_by!]

    # filter the rows returned
    where: users_bool_exp
  ): users_aggregate!

  # fetch data from the table: "users" using primary key columns
  users_by_pk(id: bigint!): users

  # fetch data from the table: "votes"
  votes(
    # distinct select on columns
    distinct_on: [votes_select_column!]

    # limit the nuber of rows returned
    limit: Int

    # skip the first n rows. Use only with order_by
    offset: Int

    # sort the rows by one or more columns
    order_by: [votes_order_by!]

    # filter the rows returned
    where: votes_bool_exp
  ): [votes!]!

  # fetch aggregated fields from the table: "votes"
  votes_aggregate(
    # distinct select on columns
    distinct_on: [votes_select_column!]

    # limit the nuber of rows returned
    limit: Int

    # skip the first n rows. Use only with order_by
    offset: Int

    # sort the rows by one or more columns
    order_by: [votes_order_by!]

    # filter the rows returned
    where: votes_bool_exp
  ): votes_aggregate!

  # fetch data from the table: "votes" using primary key columns
  votes_by_pk(id: bigint!): votes
}

scalar timestamp

# expression to compare columns of type timestamp. All fields are combined with logical 'AND'.
input timestamp_comparison_exp {
  _eq: timestamp
  _gt: timestamp
  _gte: timestamp
  _in: [timestamp]
  _is_null: Boolean
  _lt: timestamp
  _lte: timestamp
  _neq: timestamp
  _nin: [timestamp]
}

# columns and relationships of "user_roles"
type user_roles {
  # An object relationship
  role: roles!
  role_id: bigint!

  # An object relationship
  user: users!
  user_id: bigint!
}

# aggregated selection of "user_roles"
type user_roles_aggregate {
  aggregate: user_roles_aggregate_fields
  nodes: [user_roles!]!
}

# aggregate fields of "user_roles"
type user_roles_aggregate_fields {
  avg: user_roles_avg_fields
  count(columns: [user_roles_select_column!], distinct: Boolean): Int
  max: user_roles_max_fields
  min: user_roles_min_fields
  stddev: user_roles_stddev_fields
  stddev_pop: user_roles_stddev_pop_fields
  stddev_samp: user_roles_stddev_samp_fields
  sum: user_roles_sum_fields
  var_pop: user_roles_var_pop_fields
  var_samp: user_roles_var_samp_fields
  variance: user_roles_variance_fields
}

# order by aggregate values of table "user_roles"
input user_roles_aggregate_order_by {
  avg: user_roles_avg_order_by
  count: order_by
  max: user_roles_max_order_by
  min: user_roles_min_order_by
  stddev: user_roles_stddev_order_by
  stddev_pop: user_roles_stddev_pop_order_by
  stddev_samp: user_roles_stddev_samp_order_by
  sum: user_roles_sum_order_by
  var_pop: user_roles_var_pop_order_by
  var_samp: user_roles_var_samp_order_by
  variance: user_roles_variance_order_by
}

# input type for inserting array relation for remote table "user_roles"
input user_roles_arr_rel_insert_input {
  data: [user_roles_insert_input!]!
  on_conflict: user_roles_on_conflict
}

# aggregate avg on columns
type user_roles_avg_fields {
  role_id: Float
  user_id: Float
}

# order by avg() on columns of table "user_roles"
input user_roles_avg_order_by {
  role_id: order_by
  user_id: order_by
}

# Boolean expression to filter rows from the table "user_roles". All fields are combined with a logical 'AND'.
input user_roles_bool_exp {
  _and: [user_roles_bool_exp]
  _not: user_roles_bool_exp
  _or: [user_roles_bool_exp]
  role: roles_bool_exp
  role_id: bigint_comparison_exp
  user: users_bool_exp
  user_id: bigint_comparison_exp
}

# unique or primary key constraints on table "user_roles"
enum user_roles_constraint {
  # unique or primary key constraint
  user_roles_pkey
}

# input type for incrementing integer columne in table "user_roles"
input user_roles_inc_input {
  role_id: bigint
  user_id: bigint
}

# input type for inserting data into table "user_roles"
input user_roles_insert_input {
  role: roles_obj_rel_insert_input
  role_id: bigint
  user: users_obj_rel_insert_input
  user_id: bigint
}

# aggregate max on columns
type user_roles_max_fields {
  role_id: bigint
  user_id: bigint
}

# order by max() on columns of table "user_roles"
input user_roles_max_order_by {
  role_id: order_by
  user_id: order_by
}

# aggregate min on columns
type user_roles_min_fields {
  role_id: bigint
  user_id: bigint
}

# order by min() on columns of table "user_roles"
input user_roles_min_order_by {
  role_id: order_by
  user_id: order_by
}

# response of any mutation on the table "user_roles"
type user_roles_mutation_response {
  # number of affected rows by the mutation
  affected_rows: Int!

  # data of the affected rows by the mutation
  returning: [user_roles!]!
}

# input type for inserting object relation for remote table "user_roles"
input user_roles_obj_rel_insert_input {
  data: user_roles_insert_input!
  on_conflict: user_roles_on_conflict
}

# on conflict condition type for table "user_roles"
input user_roles_on_conflict {
  constraint: user_roles_constraint!
  update_columns: [user_roles_update_column!]!
}

# ordering options when selecting data from "user_roles"
input user_roles_order_by {
  role: roles_order_by
  role_id: order_by
  user: users_order_by
  user_id: order_by
}

# select columns of table "user_roles"
enum user_roles_select_column {
  # column name
  role_id

  # column name
  user_id
}

# input type for updating data in table "user_roles"
input user_roles_set_input {
  role_id: bigint
  user_id: bigint
}

# aggregate stddev on columns
type user_roles_stddev_fields {
  role_id: Float
  user_id: Float
}

# order by stddev() on columns of table "user_roles"
input user_roles_stddev_order_by {
  role_id: order_by
  user_id: order_by
}

# aggregate stddev_pop on columns
type user_roles_stddev_pop_fields {
  role_id: Float
  user_id: Float
}

# order by stddev_pop() on columns of table "user_roles"
input user_roles_stddev_pop_order_by {
  role_id: order_by
  user_id: order_by
}

# aggregate stddev_samp on columns
type user_roles_stddev_samp_fields {
  role_id: Float
  user_id: Float
}

# order by stddev_samp() on columns of table "user_roles"
input user_roles_stddev_samp_order_by {
  role_id: order_by
  user_id: order_by
}

# aggregate sum on columns
type user_roles_sum_fields {
  role_id: bigint
  user_id: bigint
}

# order by sum() on columns of table "user_roles"
input user_roles_sum_order_by {
  role_id: order_by
  user_id: order_by
}

# update columns of table "user_roles"
enum user_roles_update_column {
  # column name
  role_id

  # column name
  user_id
}

# aggregate var_pop on columns
type user_roles_var_pop_fields {
  role_id: Float
  user_id: Float
}

# order by var_pop() on columns of table "user_roles"
input user_roles_var_pop_order_by {
  role_id: order_by
  user_id: order_by
}

# aggregate var_samp on columns
type user_roles_var_samp_fields {
  role_id: Float
  user_id: Float
}

# order by var_samp() on columns of table "user_roles"
input user_roles_var_samp_order_by {
  role_id: order_by
  user_id: order_by
}

# aggregate variance on columns
type user_roles_variance_fields {
  role_id: Float
  user_id: Float
}

# order by variance() on columns of table "user_roles"
input user_roles_variance_order_by {
  role_id: order_by
  user_id: order_by
}

# columns and relationships of "users"
type users {
  created_at: timestamp
  email: String
  id: bigint!
  name: String
  password: String
  updated_at: timestamp

  # An array relationship
  user_roles(
    # distinct select on columns
    distinct_on: [user_roles_select_column!]

    # limit the nuber of rows returned
    limit: Int

    # skip the first n rows. Use only with order_by
    offset: Int

    # sort the rows by one or more columns
    order_by: [user_roles_order_by!]

    # filter the rows returned
    where: user_roles_bool_exp
  ): [user_roles!]!

  # An aggregated array relationship
  user_roles_aggregate(
    # distinct select on columns
    distinct_on: [user_roles_select_column!]

    # limit the nuber of rows returned
    limit: Int

    # skip the first n rows. Use only with order_by
    offset: Int

    # sort the rows by one or more columns
    order_by: [user_roles_order_by!]

    # filter the rows returned
    where: user_roles_bool_exp
  ): user_roles_aggregate!
  username: String

  # An array relationship
  votes(
    # distinct select on columns
    distinct_on: [votes_select_column!]

    # limit the nuber of rows returned
    limit: Int

    # skip the first n rows. Use only with order_by
    offset: Int

    # sort the rows by one or more columns
    order_by: [votes_order_by!]

    # filter the rows returned
    where: votes_bool_exp
  ): [votes!]!

  # An aggregated array relationship
  votes_aggregate(
    # distinct select on columns
    distinct_on: [votes_select_column!]

    # limit the nuber of rows returned
    limit: Int

    # skip the first n rows. Use only with order_by
    offset: Int

    # sort the rows by one or more columns
    order_by: [votes_order_by!]

    # filter the rows returned
    where: votes_bool_exp
  ): votes_aggregate!
}

# aggregated selection of "users"
type users_aggregate {
  aggregate: users_aggregate_fields
  nodes: [users!]!
}

# aggregate fields of "users"
type users_aggregate_fields {
  avg: users_avg_fields
  count(columns: [users_select_column!], distinct: Boolean): Int
  max: users_max_fields
  min: users_min_fields
  stddev: users_stddev_fields
  stddev_pop: users_stddev_pop_fields
  stddev_samp: users_stddev_samp_fields
  sum: users_sum_fields
  var_pop: users_var_pop_fields
  var_samp: users_var_samp_fields
  variance: users_variance_fields
}

# order by aggregate values of table "users"
input users_aggregate_order_by {
  avg: users_avg_order_by
  count: order_by
  max: users_max_order_by
  min: users_min_order_by
  stddev: users_stddev_order_by
  stddev_pop: users_stddev_pop_order_by
  stddev_samp: users_stddev_samp_order_by
  sum: users_sum_order_by
  var_pop: users_var_pop_order_by
  var_samp: users_var_samp_order_by
  variance: users_variance_order_by
}

# input type for inserting array relation for remote table "users"
input users_arr_rel_insert_input {
  data: [users_insert_input!]!
  on_conflict: users_on_conflict
}

# aggregate avg on columns
type users_avg_fields {
  id: Float
}

# order by avg() on columns of table "users"
input users_avg_order_by {
  id: order_by
}

# Boolean expression to filter rows from the table "users". All fields are combined with a logical 'AND'.
input users_bool_exp {
  _and: [users_bool_exp]
  _not: users_bool_exp
  _or: [users_bool_exp]
  created_at: timestamp_comparison_exp
  email: varchar_comparison_exp
  id: bigint_comparison_exp
  name: varchar_comparison_exp
  password: varchar_comparison_exp
  updated_at: timestamp_comparison_exp
  user_roles: user_roles_bool_exp
  username: varchar_comparison_exp
  votes: votes_bool_exp
}

# unique or primary key constraints on table "users"
enum users_constraint {
  # unique or primary key constraint
  uk6dotkott2kjsp8vw4d0m25fb7

  # unique or primary key constraint
  ukr43af9ap4edm43mmtq01oddj6

  # unique or primary key constraint
  users_pkey
}

# input type for incrementing integer columne in table "users"
input users_inc_input {
  id: bigint
}

# input type for inserting data into table "users"
input users_insert_input {
  created_at: timestamp
  email: String
  id: bigint
  name: String
  password: String
  updated_at: timestamp
  user_roles: user_roles_arr_rel_insert_input
  username: String
  votes: votes_arr_rel_insert_input
}

# aggregate max on columns
type users_max_fields {
  email: String
  id: bigint
  name: String
  password: String
  username: String
}

# order by max() on columns of table "users"
input users_max_order_by {
  email: order_by
  id: order_by
  name: order_by
  password: order_by
  username: order_by
}

# aggregate min on columns
type users_min_fields {
  email: String
  id: bigint
  name: String
  password: String
  username: String
}

# order by min() on columns of table "users"
input users_min_order_by {
  email: order_by
  id: order_by
  name: order_by
  password: order_by
  username: order_by
}

# response of any mutation on the table "users"
type users_mutation_response {
  # number of affected rows by the mutation
  affected_rows: Int!

  # data of the affected rows by the mutation
  returning: [users!]!
}

# input type for inserting object relation for remote table "users"
input users_obj_rel_insert_input {
  data: users_insert_input!
  on_conflict: users_on_conflict
}

# on conflict condition type for table "users"
input users_on_conflict {
  constraint: users_constraint!
  update_columns: [users_update_column!]!
}

# ordering options when selecting data from "users"
input users_order_by {
  created_at: order_by
  email: order_by
  id: order_by
  name: order_by
  password: order_by
  updated_at: order_by
  user_roles_aggregate: user_roles_aggregate_order_by
  username: order_by
  votes_aggregate: votes_aggregate_order_by
}

# select columns of table "users"
enum users_select_column {
  # column name
  created_at

  # column name
  email

  # column name
  id

  # column name
  name

  # column name
  password

  # column name
  updated_at

  # column name
  username
}

# input type for updating data in table "users"
input users_set_input {
  created_at: timestamp
  email: String
  id: bigint
  name: String
  password: String
  updated_at: timestamp
  username: String
}

# aggregate stddev on columns
type users_stddev_fields {
  id: Float
}

# order by stddev() on columns of table "users"
input users_stddev_order_by {
  id: order_by
}

# aggregate stddev_pop on columns
type users_stddev_pop_fields {
  id: Float
}

# order by stddev_pop() on columns of table "users"
input users_stddev_pop_order_by {
  id: order_by
}

# aggregate stddev_samp on columns
type users_stddev_samp_fields {
  id: Float
}

# order by stddev_samp() on columns of table "users"
input users_stddev_samp_order_by {
  id: order_by
}

# aggregate sum on columns
type users_sum_fields {
  id: bigint
}

# order by sum() on columns of table "users"
input users_sum_order_by {
  id: order_by
}

# update columns of table "users"
enum users_update_column {
  # column name
  created_at

  # column name
  email

  # column name
  id

  # column name
  name

  # column name
  password

  # column name
  updated_at

  # column name
  username
}

# aggregate var_pop on columns
type users_var_pop_fields {
  id: Float
}

# order by var_pop() on columns of table "users"
input users_var_pop_order_by {
  id: order_by
}

# aggregate var_samp on columns
type users_var_samp_fields {
  id: Float
}

# order by var_samp() on columns of table "users"
input users_var_samp_order_by {
  id: order_by
}

# aggregate variance on columns
type users_variance_fields {
  id: Float
}

# order by variance() on columns of table "users"
input users_variance_order_by {
  id: order_by
}

# expression to compare columns of type varchar. All fields are combined with logical 'AND'.
input varchar_comparison_exp {
  _eq: String
  _gt: String
  _gte: String
  _ilike: String
  _in: [String]
  _is_null: Boolean
  _like: String
  _lt: String
  _lte: String
  _neq: String
  _nilike: String
  _nin: [String]
  _nlike: String
  _nsimilar: String
  _similar: String
}

# columns and relationships of "votes"
type votes {
  # An object relationship
  choice: choices!
  choice_id: bigint!
  created_at: timestamp
  id: bigint!

  # An object relationship
  poll: polls!
  poll_id: bigint!
  updated_at: timestamp

  # An object relationship
  user: users!
  user_id: bigint!
}

# aggregated selection of "votes"
type votes_aggregate {
  aggregate: votes_aggregate_fields
  nodes: [votes!]!
}

# aggregate fields of "votes"
type votes_aggregate_fields {
  avg: votes_avg_fields
  count(columns: [votes_select_column!], distinct: Boolean): Int
  max: votes_max_fields
  min: votes_min_fields
  stddev: votes_stddev_fields
  stddev_pop: votes_stddev_pop_fields
  stddev_samp: votes_stddev_samp_fields
  sum: votes_sum_fields
  var_pop: votes_var_pop_fields
  var_samp: votes_var_samp_fields
  variance: votes_variance_fields
}

# order by aggregate values of table "votes"
input votes_aggregate_order_by {
  avg: votes_avg_order_by
  count: order_by
  max: votes_max_order_by
  min: votes_min_order_by
  stddev: votes_stddev_order_by
  stddev_pop: votes_stddev_pop_order_by
  stddev_samp: votes_stddev_samp_order_by
  sum: votes_sum_order_by
  var_pop: votes_var_pop_order_by
  var_samp: votes_var_samp_order_by
  variance: votes_variance_order_by
}

# input type for inserting array relation for remote table "votes"
input votes_arr_rel_insert_input {
  data: [votes_insert_input!]!
  on_conflict: votes_on_conflict
}

# aggregate avg on columns
type votes_avg_fields {
  choice_id: Float
  id: Float
  poll_id: Float
  user_id: Float
}

# order by avg() on columns of table "votes"
input votes_avg_order_by {
  choice_id: order_by
  id: order_by
  poll_id: order_by
  user_id: order_by
}

# Boolean expression to filter rows from the table "votes". All fields are combined with a logical 'AND'.
input votes_bool_exp {
  _and: [votes_bool_exp]
  _not: votes_bool_exp
  _or: [votes_bool_exp]
  choice: choices_bool_exp
  choice_id: bigint_comparison_exp
  created_at: timestamp_comparison_exp
  id: bigint_comparison_exp
  poll: polls_bool_exp
  poll_id: bigint_comparison_exp
  updated_at: timestamp_comparison_exp
  user: users_bool_exp
  user_id: bigint_comparison_exp
}

# unique or primary key constraints on table "votes"
enum votes_constraint {
  # unique or primary key constraint
  uk8um9h2wxsdjrgx3rjjwvny676

  # unique or primary key constraint
  votes_pkey
}

# input type for incrementing integer columne in table "votes"
input votes_inc_input {
  choice_id: bigint
  id: bigint
  poll_id: bigint
  user_id: bigint
}

# input type for inserting data into table "votes"
input votes_insert_input {
  choice: choices_obj_rel_insert_input
  choice_id: bigint
  created_at: timestamp
  id: bigint
  poll: polls_obj_rel_insert_input
  poll_id: bigint
  updated_at: timestamp
  user: users_obj_rel_insert_input
  user_id: bigint
}

# aggregate max on columns
type votes_max_fields {
  choice_id: bigint
  id: bigint
  poll_id: bigint
  user_id: bigint
}

# order by max() on columns of table "votes"
input votes_max_order_by {
  choice_id: order_by
  id: order_by
  poll_id: order_by
  user_id: order_by
}

# aggregate min on columns
type votes_min_fields {
  choice_id: bigint
  id: bigint
  poll_id: bigint
  user_id: bigint
}

# order by min() on columns of table "votes"
input votes_min_order_by {
  choice_id: order_by
  id: order_by
  poll_id: order_by
  user_id: order_by
}

# response of any mutation on the table "votes"
type votes_mutation_response {
  # number of affected rows by the mutation
  affected_rows: Int!

  # data of the affected rows by the mutation
  returning: [votes!]!
}

# input type for inserting object relation for remote table "votes"
input votes_obj_rel_insert_input {
  data: votes_insert_input!
  on_conflict: votes_on_conflict
}

# on conflict condition type for table "votes"
input votes_on_conflict {
  constraint: votes_constraint!
  update_columns: [votes_update_column!]!
}

# ordering options when selecting data from "votes"
input votes_order_by {
  choice: choices_order_by
  choice_id: order_by
  created_at: order_by
  id: order_by
  poll: polls_order_by
  poll_id: order_by
  updated_at: order_by
  user: users_order_by
  user_id: order_by
}

# select columns of table "votes"
enum votes_select_column {
  # column name
  choice_id

  # column name
  created_at

  # column name
  id

  # column name
  poll_id

  # column name
  updated_at

  # column name
  user_id
}

# input type for updating data in table "votes"
input votes_set_input {
  choice_id: bigint
  created_at: timestamp
  id: bigint
  poll_id: bigint
  updated_at: timestamp
  user_id: bigint
}

# aggregate stddev on columns
type votes_stddev_fields {
  choice_id: Float
  id: Float
  poll_id: Float
  user_id: Float
}

# order by stddev() on columns of table "votes"
input votes_stddev_order_by {
  choice_id: order_by
  id: order_by
  poll_id: order_by
  user_id: order_by
}

# aggregate stddev_pop on columns
type votes_stddev_pop_fields {
  choice_id: Float
  id: Float
  poll_id: Float
  user_id: Float
}

# order by stddev_pop() on columns of table "votes"
input votes_stddev_pop_order_by {
  choice_id: order_by
  id: order_by
  poll_id: order_by
  user_id: order_by
}

# aggregate stddev_samp on columns
type votes_stddev_samp_fields {
  choice_id: Float
  id: Float
  poll_id: Float
  user_id: Float
}

# order by stddev_samp() on columns of table "votes"
input votes_stddev_samp_order_by {
  choice_id: order_by
  id: order_by
  poll_id: order_by
  user_id: order_by
}

# aggregate sum on columns
type votes_sum_fields {
  choice_id: bigint
  id: bigint
  poll_id: bigint
  user_id: bigint
}

# order by sum() on columns of table "votes"
input votes_sum_order_by {
  choice_id: order_by
  id: order_by
  poll_id: order_by
  user_id: order_by
}

# update columns of table "votes"
enum votes_update_column {
  # column name
  choice_id

  # column name
  created_at

  # column name
  id

  # column name
  poll_id

  # column name
  updated_at

  # column name
  user_id
}

# aggregate var_pop on columns
type votes_var_pop_fields {
  choice_id: Float
  id: Float
  poll_id: Float
  user_id: Float
}

# order by var_pop() on columns of table "votes"
input votes_var_pop_order_by {
  choice_id: order_by
  id: order_by
  poll_id: order_by
  user_id: order_by
}

# aggregate var_samp on columns
type votes_var_samp_fields {
  choice_id: Float
  id: Float
  poll_id: Float
  user_id: Float
}

# order by var_samp() on columns of table "votes"
input votes_var_samp_order_by {
  choice_id: order_by
  id: order_by
  poll_id: order_by
  user_id: order_by
}

# aggregate variance on columns
type votes_variance_fields {
  choice_id: Float
  id: Float
  poll_id: Float
  user_id: Float
}

# order by variance() on columns of table "votes"
input votes_variance_order_by {
  choice_id: order_by
  id: order_by
  poll_id: order_by
  user_id: order_by
}

```

**Comment by mweststrate** [comment]
That is really too much info to work with :). Could trim down the model so
that it becomes the minimal model that is needed to reproduce the issue?
Note that there can be two causes, so best find to try out which one it it
is when reducing the model:

1. There is some schema construction in there, which might not be that
common, that generates code that results in the a circular dep and therefor
the error
2. The model is simply to big and TypeScript's type inference simply gives
up (there are some hardcoded magic numbers in there), and regardless what
you remove, but trimming it down in one direction or another, it starts
working again

**Comment by beepsoft** [comment]
Yeah, I know this is big and complex, but that's what Hasura generates. (Btw. you mentioned Hasura in your mst-gql talk, that's why I gave it a try to see how/if it works :-) ).

Anyway, I will experiment with it some to see which definitions cause the problem.

**Comment by beepsoft** [comment]
I couldn't really find I way to work around this. @mweststrate is there any chance for you to try mst-gql with an actual Hasura generated schema? Using the two together would be really great!

**Comment by mweststrate** [comment]
Sorry, I'm not really personally involved in maintaining this package, just
wanted to provide the head start after many requests. But I have no
projects currently in which I'm using it, nor do I have the time &
motivation left to maintain this package. So if this package will benefit
you significantly, I'll recommend to dive a bit deeper in it. This package
is really going to be a community effort or nothing :)

**Comment by chrisdrackett** [comment]
@beepsoft I'm going to close this as we have #45, but feel free to open other issues related to Hasura if needed!
